_wandb:
    value:
        cli_version: 0.26.0
        e:
            57c3nsjfxdz5qs7vpylnmfx5xzb6rfo3:
                args:
                    - fit
                    - --config
                    - /usrhomes/s1501/st182046/dirichlet/GMM/configs/target_adaptation.yaml
                codePath: main.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1888558305280"
                        used: "131787128832"
                email: st182046@stud.uni-stuttgart.de
                executable: /misc/usrhomes/s1501/st182046/dirichlet/GMM/venv/bin/python
                git:
                    commit: 2c601f6a8df1796d67071a382b51c17fc5c1805d
                    remote: https://github.com/xaaxcvb-cell/XuZhangst182046.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-a15fa5f5-5388-b8de-fcae-6c07b8f6083d
                host: linse2
                memory:
                    total: "135036313600"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /misc/usrhomes/s1501/st182046/dirichlet/GMM/main.py
                python: CPython 3.12.12
                root: /misc/usrhomes/s1501/st182046/dirichlet/GMM/configs
                slurm:
                    cluster_name: compute-cluster
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "2"
                    cpus_per_task: "2"
                    gpus: "1"
                    gtids: "0"
                    job_account: s1501
                    job_cpus_per_node: "2"
                    job_gid: "222"
                    job_gpus: "1"
                    job_id: "202617"
                    job_name: Dirichlet
                    job_nodelist: linse2
                    job_num_nodes: "1"
                    job_partition: stud
                    job_qos: batch
                    job_uid: "11501"
                    job_user: s1501
                    jobid: "202617"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: linse2
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /misc/usrhomes/s1501/st182046/dirichlet/GMM
                    submit_host: login1
                    task_pid: "1904657"
                    tasks_per_node: "1"
                    topology_addr: linse2
                    topology_addr_pattern: node
                    working_cluster: compute-cluster:slurm-ctrl:6817:8960:109
                startedAt: "2026-04-21T13:46:12.604641Z"
                writerId: 57c3nsjfxdz5qs7vpylnmfx5xzb6rfo3
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 106
            "2":
                - 1
                - 41
                - 51
                - 106
            "3":
                - 13
                - 41
                - 61
            "4": 3.12.12
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
