# lightning.pytorch==2.0.0
seed_everything: True
trainer:
  accelerator: auto
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
    class_path: TensorBoardLogger
    init_args:
      # select logging path
      save_dir: 'logs'
      name: 'visda'         #n1    #DomainNet , 'visda' 
  log_every_n_steps: 5
  max_epochs: 1
  min_epochs: null
  check_val_every_n_epoch: 1
  enable_checkpointing: False
model:
  class_path: adaptation.GmmBaAdaptationModule
  init_args: 
    # select hyperparameters
    feature_dim: 256  # choose same number of feature dimensions as used for the source model (default is 256)
    lr: 1e-1   # we used 1e-2 for VisDA-C and 1e-3 for DomainNet ###0.1 for Dirichlet Visda
    red_feature_dim: 64
    p_reject: 0.5
    N_init: 30
    augmentation: True
    lam: 1
    temperature: 0.1
    ckpt_dir: 'source_models/visda/source_model_ODA/checkpoints/source_ckpt.pt' 
    #n2  #'source_models/visda/source_model_ODA/checkpoints/source_ckpt.pt' ###PDA,ODA,OPDA  # select pre-trained source model matching the desired source domain and category shift
    #n2  #'source_models/domainnet/sketch_source/source_model_OPDA/checkpoints/source_ckpt.pt'
    #16.04
    #replay_capacity: 1000
    #replay_batch_size: 64
    #replay_start_size: 64
    #replay_store_mode: "rejected"
data:
  class_path: datasets.VisDADataModule  #n3 #datasets.VisDADataModule  # change to datasets.DomainNetDataModule for DomainNet dataset
  init_args:
    batch_size: 64
    category_shift: 'ODA' #n4  # select category shift1          ###PDA,ODA,OPDA
    test_domain: 'validation' #n5   # select target domain   
         ###VisDA: 'validation' DomainNet:'clipart'，'painting'，'real'，'sketch'

