_wandb:
    value:
        cli_version: 0.26.0
        e:
            fxpsuoawp97w66viyhgn5x256zoz4bnv:
                args:
                    - fit
                    - --config
                    - /usrhomes/s1501/st182046/dirichlet/GMM/configs/target_adaptation.yaml
                codePath: main.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "527836135424"
                        used: "250105413632"
                email: st182046@stud.uni-stuttgart.de
                executable: /misc/usrhomes/s1501/st182046/dirichlet/GMM/venv/bin/python
                git:
                    commit: 2c601f6a8df1796d67071a382b51c17fc5c1805d
                    remote: https://github.com/xaaxcvb-cell/XuZhangst182046.git
                gpu: NVIDIA RTX A5000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-a7124ec3-7d3e-aaff-408f-411e4f92470f
                host: linse19
                memory:
                    total: "270083911680"
                os: Linux-6.8.0-107-generic-x86_64-with-glibc2.39
                program: /misc/usrhomes/s1501/st182046/dirichlet/GMM/main.py
                python: CPython 3.12.12
                root: /misc/usrhomes/s1501/st182046/dirichlet/GMM/configs
                slurm:
                    cluster_name: compute-cluster
                    conf: /var/spool/slurm/d/conf-cache/slurm.conf
                    cpus_on_node: "2"
                    cpus_per_task: "2"
                    gpus: "1"
                    gtids: "0"
                    job_account: s1501
                    job_cpus_per_node: "2"
                    job_gid: "222"
                    job_gpus: "1"
                    job_id: "202438"
                    job_name: Dirichlet
                    job_nodelist: linse19
                    job_num_nodes: "1"
                    job_partition: stud
                    job_qos: batch
                    job_uid: "11501"
                    job_user: s1501
                    jobid: "202438"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: linse19
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /misc/usrhomes/s1501/st182046/dirichlet/GMM
                    submit_host: login1
                    task_pid: "1785219"
                    tasks_per_node: "1"
                    topology_addr: linse19
                    topology_addr_pattern: node
                    working_cluster: compute-cluster:slurm-ctrl:6817:8960:109
                startedAt: "2026-04-21T00:45:09.761900Z"
                writerId: fxpsuoawp97w66viyhgn5x256zoz4bnv
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 106
            "2":
                - 1
                - 41
                - 51
                - 106
            "3":
                - 13
                - 41
                - 61
            "4": 3.12.12
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
